load("@pip//:requirements.bzl", "requirement")
load("@rules_python//python:defs.bzl", "py_binary", "py_library")

py_binary(
    name = "triton_example",
    srcs = ["triton_example.py"],
    main = "triton_example.py",
    deps = [
    ],
)
