# Default values for foxglove-studio.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1
ingress:
  enabled: true
  hosts:
    - host: studio.ingress.k8s.cn
      paths:
        - path: /
          pathType: ImplementationSpecific
