load("@rules_cc//cc:defs.bzl", "cc_binary")

package(
    default_visibility = ["//visibility:public"],
)

cc_binary(
    name = "arrow_example",
    srcs = ["arrow_example.cc"],
    deps = [
        "@arrow",
    ],
)